/* do not change this file, it is auto generated by storybook. */

import {
  configure,
  addDecorator,
  addParameters,
  addArgsEnhancer,
  clearDecorators,
} from '@storybook/react-native';

import { decorators, parameters } from './preview';

if (decorators) {
  if (__DEV__) {
    // stops the warning from showing on every HMR
    require('react-native').LogBox.ignoreLogs([
      '`clearDecorators` is deprecated and will be removed in Storybook 7.0',
    ]);
  }
  // workaround for global decorators getting duplicated on hmr
  clearDecorators();
  decorators.forEach((decorator) => addDecorator(decorator));
}

if (parameters) {
  addParameters(parameters);
}

try {
  configure(() => {
    require('../src/components/Button.stories.tsx');
    require('../src/components/Input.stories.tsx');
    require('../src/components/Icons.stories.tsx');
  }, module, false);
} catch (e) {
  console.error(e);
}

const getStories = () => {
  return {
    './src/components/Button.stories.tsx': require('../src/components/Button.stories.tsx'),
    './src/components/Input.stories.tsx': require('../src/components/Input.stories.tsx'),
    './src/components/Icons.stories.tsx': require('../src/components/Icons.stories.tsx'),
  };
};

export const view = {
  getStorybookUI: require('@storybook/react-native').getStorybookUI,
};

export { configure, getStories };
